### ISSUE TITLE
Upgrade to JavaFX 11+, Latest Gradle, JDK 11-17, Latest Groovy JavaFX Plugin, etc.

### ISSUE THREAD

**Issue by msgilligan** [aalmiray/groovy-console-fx#5]
@aalmiray An interest in updating this project?

I can't get it to build and run on macOS.

```
sdk use java 8.0.302.fx-librca
./gradlew run --info
```
gets me this far:

```
Exception in Application init method
[main] ERROR griffon.core.GriffonExceptionHandler - Uncaught Exception. Stacktrace was sanitized. Set System property 'griffon.full.stacktrace' to 'true' for full report.
java.lang.RuntimeException: Exception in Application init method
Caused by: griffon.exceptions.InstanceNotFoundException: Could not find an instance of type griffon.core.PlatformHandler
        at griffon.javafx.AbstractJavaFXGriffonApplication.initialize(AbstractJavaFXGriffonApplication.java:314)
        at griffon.javafx.JavaFXGriffonApplication.afterInit(JavaFXGriffonApplication.java:75)
        at griffon.javafx.JavaFXGriffonApplication.init(JavaFXGriffonApplication.java:71)
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, griffon.exceptions.TypeNotFoundException: Could not find type griffon.core.PlatformHandler
  while locating org.codehaus.griffon.runtime.core.PlatformHandlerProvider
  at org.codehaus.griffon.runtime.injection.GuiceInjector$1.handleBinding(GuiceInjector.java:94)
  while locating griffon.core.PlatformHandler

1 error
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
        ... 3 more
Caused by: griffon.exceptions.TypeNotFoundException: Could not find type griffon.core.PlatformHandler
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:77)
        at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:66)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
        ... 4 more
Caused by: java.lang.NoClassDefFoundError: com/apple/mrj/MRJAboutHandler
        ... 16 more
Caused by: java.lang.ClassNotFoundException: com.apple.mrj.MRJAboutHandler
        ... 16 more

> Task :run FAILED
:run (Thread[Task worker for ':',5,main]) completed. Took 3.13 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Users/sean/.sdkman/candidates/java/8.0.302.fx-librca/bin/java'' finished with non-zero exit value 1
```

**Comment by msgilligan** [comment]
I tried upgrading a JDK 11 with bundled JavaFX, I tried newer Gradle, etc. but got worse results in almost every case.

It seems like upgrading to JDK 11, some newer Gradle, and the OpenJFX JavaFX plugin is probably the best path. Any ideas?
